### ISSUE TITLE
Unable to make fuse mode connection with 2730

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [Enterprise-connect/ec-x-sdk#76]
I am trying to play with 2730 version and trying to make EC connections with that version.

- I am able to make successful direct EC connection 
- I am able to make encryption, decryption and signature verification
- Trying to make EC connection with fuse mode and able to make super connection between gateway and server agent. After running the client agent and trying to make EC connection, client logs shows - 

```
[EC Client x0] 2020/03/29 19:08:24 [proxy has been unset for the url: http://localhost:8001/agent]
 [EC Client x0] 2020/03/29 19:08:24 [http proxy was not used for the request: http://localhost:8001/agent]
 [EC Client x0] 2020/03/29 19:08:26 [error while adding the client inst.]
 [EC Client x0] 2020/03/29 19:08:26 [github.build.ge.com/212359746/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
```

From the experience, ```bad handshake``` error comes when client agent unable to find the target (server) agent. But I reverified all the details and did not find any issue in server or client scripts.

**Comment by ramaraosrikakulapu** [comment]
Here are the scripts skeletons - 

**gwserver.yml**

```
ec-config:
  conf:
    mod: gw:server
    gpt : ":8001"
    zon: {zone-id}
    sst: https://{zone-id}.run.aws-usw02-dev.ice.predix.io/v1beta
    tkn: {admin token}
    hst: ws://localhost:8001/agent
    dbg: true
    aid: {agent id}
    grp: {group name}
    cid: {client id}
    csc: {client secret}
    dur: 300
    oa2: https://{oauth2 URI}/oauth/token
    rht: localhost
    rpt: ":5432"

```

**Client script:**

```
./agent_darwin_sys_2730 -mod client -aid {agent id} -tid {target id} -zon {zone id} -grp {group name} -sst https://{zone-id}.run.aws-usw02-dev.ice.predix.io/v1beta -hst ws://localhost:8001/agent  -cid {client id} -csc {client secret} -oa2 https://{oauth2 URI}/oauth/token -dur 1200 -lpt :6192 -dbg
```

Please let me know, if I can provide more details
